name: Update nuget dependencies
on: 
  push:
    branches:
      - "update"
  # schedule:
  #   - cron: '0 8 * * 5' # every friday AM 8:00


jobs:
  build:
    name: "Update all nugets to latest version"
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install

    - name: update packages
      run: npm update

    - name: list outdated
      run: |
        OUTDATED=$(npm outdated)
        echo "::set-output name=OUTDATED::$OUTDATED"
      id: check

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Updated npm dependencies"
        body: ${{ steps.check.outputs.OUTDATED }}
        reviewers: tjololo
        labels: dependencies