name: Pull Request build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build pull request"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ github.repository }}:test
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
